version: '3.7'

services:
  pg:
    image: postgres:12
    container_name: pg-container
    volumes:
    - ${DB_DATAPATH}:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
